[package]
name = "proyectoGPT"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
#rand = "0.9.2"
randomizer = "0.1.2"
chrono = "0.4.42"
once_cell = "1.21.3"
